### ISSUE TITLE
Can't compile with MinGW (Win8 x64)

### ISSUE THREAD

**Issue by WesleyCeraso** [hunter-packages/gtest#1]
Hi, I can't compile the Hunter's GTest package with MinGW. The package provided by google compiles without problems.

I'm using g++ (i686-posix-dwarf-rev1, Built by MinGW-W64 project) 4.9.2 that comes along with Qt 5.5.

The build step output:

$ cmake --build .
[ 25%] Building CXX object CMakeFiles/gtest.dir/src/gtest-all.cc.obj
In file included from C:/Users/wprudencio/gtest-1.7.0-hunter-11/include/gtest/internal/gtest-internal.h:40:0,
                 from C:/Users/wprudencio/gtest-1.7.0-hunter-11/include/gtest/gtest.h:58,
                 from C:\Users\wprudencio\gtest-1.7.0-hunter-11\src\gtest-all.cc:39:
C:/Users/wprudencio/gtest-1.7.0-hunter-11/include/gtest/internal/gtest-port.h:1704:3: error: 'AutoHandle' does not name a type
   AutoHandle thread_;
   ^
In file included from C:\Users\wprudencio\gtest-1.7.0-hunter-11\src\gtest-all.cc:43:0:
C:/Users/wprudencio/gtest-1.7.0-hunter-11/src/gtest-death-test.cc:626:3: error: 'AutoHandle' does not name a type
   AutoHandle write_handle_;
   ^
C:/Users/wprudencio/gtest-1.7.0-hunter-11/src/gtest-death-test.cc:628:3: error: 'AutoHandle' does not name a type
   AutoHandle child_handle_;
   ^
C:/Users/wprudencio/gtest-1.7.0-hunter-11/src/gtest-death-test.cc:633:3: error: 'AutoHandle' does not name a type
   AutoHandle event_handle_;
   ^
C:/Users/wprudencio/gtest-1.7.0-hunter-11/src/gtest-death-test.cc: In member function 'virtual int testing::internal::WindowsDeathTest::Wait()':
C:/Users/wprudencio/gtest-1.7.0-hunter-11/src/gtest-death-test.cc:645:36: error: 'child_handle_' was not declared in this scope
   const HANDLE wait_handles[2] = { child_handle_.Get(), event_handle_.Get() };
                                    ^
C:/Users/wprudencio/gtest-1.7.0-hunter-11/src/gtest-death-test.cc:645:57: error: 'event_handle_' was not declared in this scope
   const HANDLE wait_handles[2] = { child_handle_.Get(), event_handle_.Get() };
                                                         ^
C:/Users/wprudencio/gtest-1.7.0-hunter-11/src/gtest-death-test.cc:659:3: error: 'write_handle_' was not declared in this scope
   write_handle_.Reset();
   ^
C:/Users/wprudencio/gtest-1.7.0-hunter-11/src/gtest-death-test.cc: In member function 'virtual testing::internal::DeathTest::TestRole testing::internal::WindowsDeathTest::AssumeRole()':
C:/Users/wprudencio/gtest-1.7.0-hunter-11/src/gtest-death-test.cc:709:3: error: 'write_handle_' was not declared in this scope
   write_handle_.Reset(write_handle);
   ^
C:/Users/wprudencio/gtest-1.7.0-hunter-11/src/gtest-death-test.cc:710:3: error: 'event_handle_' was not declared in this scope
   event_handle_.Reset(::CreateEvent(
   ^
C:/Users/wprudencio/gtest-1.7.0-hunter-11/src/gtest-death-test.cc:766:3: error: 'child_handle_' was not declared in this scope
   child_handle_.Reset(process_info.hProcess);
   ^
C:/Users/wprudencio/gtest-1.7.0-hunter-11/src/gtest-death-test.cc: In function 'int testing::internal::GetStatusFileDescriptor(unsigned int, size_t, size_t)':
C:/Users/wprudencio/gtest-1.7.0-hunter-11/src/gtest-death-test.cc:1232:3: error: 'AutoHandle' was not declared in this scope
   AutoHandle parent_process_handle(::OpenProcess(PROCESS_DUP_HANDLE,
   ^
C:/Users/wprudencio/gtest-1.7.0-hunter-11/src/gtest-death-test.cc:1235:7: error: 'parent_process_handle' was not declared in this scope
   if (parent_process_handle.Get() == INVALID_HANDLE_VALUE) {
       ^
C:/Users/wprudencio/gtest-1.7.0-hunter-11/src/gtest-death-test.cc:1251:26: error: 'parent_process_handle' was not declared in this scope
   if (!::DuplicateHandle(parent_process_handle.Get(), write_handle,
                          ^
C:/Users/wprudencio/gtest-1.7.0-hunter-11/src/gtest-death-test.cc:1266:26: error: 'parent_process_handle' was not declared in this scope
   if (!::DuplicateHandle(parent_process_handle.Get(), event_handle,
                          ^
In file included from C:\Users\wprudencio\gtest-1.7.0-hunter-11\src\gtest-all.cc:45:0:
C:/Users/wprudencio/gtest-1.7.0-hunter-11/src/gtest-port.cc: In function 'void testing::internal::SleepMilliseconds(int)':
C:/Users/wprudencio/gtest-1.7.0-hunter-11/src/gtest-port.cc:139:6: error: redefinition of 'void testing::internal::SleepMilliseconds(int)'
 void SleepMilliseconds(int n) {
      ^
In file included from C:/Users/wprudencio/gtest-1.7.0-hunter-11/include/gtest/internal/gtest-internal.h:40:0,
                 from C:/Users/wprudencio/gtest-1.7.0-hunter-11/include/gtest/gtest.h:58,
                 from C:\Users\wprudencio\gtest-1.7.0-hunter-11\src\gtest-all.cc:39:
C:/Users/wprudencio/gtest-1.7.0-hunter-11/include/gtest/internal/gtest-port.h:1377:13: note: 'void testing::internal::SleepMilliseconds(int)' previously defined here
 inline void SleepMilliseconds(int n) {
             ^
In file included from C:\Users\wprudencio\gtest-1.7.0-hunter-11\src\gtest-all.cc:45:0:
C:/Users/wprudencio/gtest-1.7.0-hunter-11/src/gtest-port.cc: At global scope:
C:/Users/wprudencio/gtest-1.7.0-hunter-11/src/gtest-port.cc:143:1: error: 'AutoHandle' does not name a type
 AutoHandle::AutoHandle()
 ^
C:/Users/wprudencio/gtest-1.7.0-hunter-11/src/gtest-port.cc:146:1: error: 'AutoHandle' does not name a type
 AutoHandle::AutoHandle(Handle handle)
 ^
C:/Users/wprudencio/gtest-1.7.0-hunter-11/src/gtest-port.cc:149:1: error: 'AutoHandle' does not name a type
 AutoHandle::~AutoHandle() {
 ^
C:/Users/wprudencio/gtest-1.7.0-hunter-11/src/gtest-port.cc:153:1: error: 'AutoHandle' does not name a type
 AutoHandle::Handle AutoHandle::Get() const {
 ^
C:/Users/wprudencio/gtest-1.7.0-hunter-11/src/gtest-port.cc:157:6: error: 'AutoHandle' has not been declared
 void AutoHandle::Reset() {
      ^
C:/Users/wprudencio/gtest-1.7.0-hunter-11/src/gtest-port.cc: In function 'void testing::internal::Reset()':
C:/Users/wprudencio/gtest-1.7.0-hunter-11/src/gtest-port.cc:158:29: error: too many arguments to function 'void testing::internal::Reset()'
   Reset(INVALID_HANDLE_VALUE);
                             ^
C:/Users/wprudencio/gtest-1.7.0-hunter-11/src/gtest-port.cc:157:6: note: declared here
 void AutoHandle::Reset() {
      ^
C:/Users/wprudencio/gtest-1.7.0-hunter-11/src/gtest-port.cc: At global scope:
C:/Users/wprudencio/gtest-1.7.0-hunter-11/src/gtest-port.cc:161:6: error: 'AutoHandle' has not been declared
 void AutoHandle::Reset(HANDLE handle) {
      ^
C:/Users/wprudencio/gtest-1.7.0-hunter-11/src/gtest-port.cc: In function 'void testing::internal::Reset(HANDLE)':
C:/Users/wprudencio/gtest-1.7.0-hunter-11/src/gtest-port.cc:163:7: error: 'handle_' was not declared in this scope
   if (handle_ != handle) {
       ^
C:/Users/wprudencio/gtest-1.7.0-hunter-11/src/gtest-port.cc:164:21: error: 'IsCloseable' was not declared in this scope
     if (IsCloseable()) {
                     ^
In file included from C:/Users/wprudencio/gtest-1.7.0-hunter-11/include/gtest/internal/gtest-internal.h:40:0,
                 from C:/Users/wprudencio/gtest-1.7.0-hunter-11/include/gtest/gtest.h:58,
                 from C:\Users\wprudencio\gtest-1.7.0-hunter-11\src\gtest-all.cc:39:
C:/Users/wprudencio/gtest-1.7.0-hunter-11/src/gtest-port.cc:169:31: error: 'IsCloseable' was not declared in this scope
     GTEST_CHECK_(!IsCloseable())
                               ^
C:/Users/wprudencio/gtest-1.7.0-hunter-11/include/gtest/internal/gtest-port.h:1250:37: note: in definition of macro 'GTEST_CHECK_'
     if (::testing::internal::IsTrue(condition)) \
                                     ^
In file included from C:\Users\wprudencio\gtest-1.7.0-hunter-11\src\gtest-all.cc:45:0:
C:/Users/wprudencio/gtest-1.7.0-hunter-11/src/gtest-port.cc: At global scope:
C:/Users/wprudencio/gtest-1.7.0-hunter-11/src/gtest-port.cc:175:6: error: 'AutoHandle' has not been declared
 bool AutoHandle::IsCloseable() const {
      ^
C:/Users/wprudencio/gtest-1.7.0-hunter-11/src/gtest-port.cc:175:32: error: non-member function 'bool testing::internal::IsCloseable()' cannot have cv-qualifier
 bool AutoHandle::IsCloseable() const {
                                ^
C:/Users/wprudencio/gtest-1.7.0-hunter-11/src/gtest-port.cc: In function 'bool testing::internal::IsCloseable()':
C:/Users/wprudencio/gtest-1.7.0-hunter-11/src/gtest-port.cc:178:10: error: 'handle_' was not declared in this scope
   return handle_ != NULL && handle_ != INVALID_HANDLE_VALUE;
          ^
C:/Users/wprudencio/gtest-1.7.0-hunter-11/src/gtest-port.cc: At global scope:
C:/Users/wprudencio/gtest-1.7.0-hunter-11/src/gtest-port.cc:181:1: error: redefinition of 'testing::internal::Notification::Notification()'
 Notification::Notification()
 ^
In file included from C:/Users/wprudencio/gtest-1.7.0-hunter-11/include/gtest/internal/gtest-internal.h:40:0,
                 from C:/Users/wprudencio/gtest-1.7.0-hunter-11/include/gtest/gtest.h:58,
                 from C:\Users\wprudencio\gtest-1.7.0-hunter-11\src\gtest-all.cc:39:
C:/Users/wprudencio/gtest-1.7.0-hunter-11/include/gtest/internal/gtest-port.h:1396:3: note: 'testing::internal::Notification::Notification()' previously defined here
   Notification() : notified_(false) {
   ^
In file included from C:\Users\wprudencio\gtest-1.7.0-hunter-11\src\gtest-all.cc:45:0:
C:/Users/wprudencio/gtest-1.7.0-hunter-11/src/gtest-port.cc:189:6: error: redefinition of 'void testing::internal::Notification::Notify()'
 void Notification::Notify() {
      ^
In file included from C:/Users/wprudencio/gtest-1.7.0-hunter-11/include/gtest/internal/gtest-internal.h:40:0,
                 from C:/Users/wprudencio/gtest-1.7.0-hunter-11/include/gtest/gtest.h:58,
                 from C:\Users\wprudencio\gtest-1.7.0-hunter-11\src\gtest-all.cc:39:
C:/Users/wprudencio/gtest-1.7.0-hunter-11/include/gtest/internal/gtest-port.h:1405:8: note: 'void testing::internal::Notification::Notify()' previously defined here
   void Notify() {
        ^
In file included from C:\Users\wprudencio\gtest-1.7.0-hunter-11\src\gtest-all.cc:45:0:
C:/Users/wprudencio/gtest-1.7.0-hunter-11/src/gtest-port.cc:193:6: error: redefinition of 'void testing::internal::Notification::WaitForNotification()'
 void Notification::WaitForNotification() {
      ^
In file included from C:/Users/wprudencio/gtest-1.7.0-hunter-11/include/gtest/internal/gtest-internal.h:40:0,
                 from C:/Users/wprudencio/gtest-1.7.0-hunter-11/include/gtest/gtest.h:58,
                 from C:\Users\wprudencio\gtest-1.7.0-hunter-11\src\gtest-all.cc:39:
C:/Users/wprudencio/gtest-1.7.0-hunter-11/include/gtest/internal/gtest-port.h:1413:8: note: 'void testing::internal::Notification::WaitForNotification()' previously defined here
   void WaitForNotification() {
        ^
C:/Users/wprudencio/gtest-1.7.0-hunter-11/include/gtest/internal/gtest-port.h: In constructor 'testing::internal::Mutex::Mutex()':
C:/Users/wprudencio/gtest-1.7.0-hunter-11/include/gtest/internal/gtest-port.h:1616:13: warning: 'testing::internal::Mutex::type_' will be initialized after [-Wreorder]
   MutexType type_;
             ^
C:/Users/wprudencio/gtest-1.7.0-hunter-11/include/gtest/internal/gtest-port.h:1612:16: warning:   'unsigned int testing::internal::Mutex::owner_thread_id_' [-Wreorder]
   unsigned int owner_thread_id_;
                ^
In file included from C:\Users\wprudencio\gtest-1.7.0-hunter-11\src\gtest-all.cc:45:0:
C:/Users/wprudencio/gtest-1.7.0-hunter-11/src/gtest-port.cc:198:1: warning:   when initialized here [-Wreorder]
 Mutex::Mutex()
 ^
C:/Users/wprudencio/gtest-1.7.0-hunter-11/src/gtest-port.cc: In constructor 'testing::internal::ThreadWithParamBase::ThreadWithParamBase(testing::internal::ThreadWithParamBase::Runnable_, testing::internal::Notification_)':
C:/Users/wprudencio/gtest-1.7.0-hunter-11/src/gtest-port.cc:337:9: error: class 'testing::internal::ThreadWithParamBase' does not have any field named 'thread_'
       : thread_(ThreadWithParamSupport::CreateThread(runnable,
         ^
In file included from C:/Users/wprudencio/gtest-1.7.0-hunter-11/include/gtest/internal/gtest-internal.h:40:0,
                 from C:/Users/wprudencio/gtest-1.7.0-hunter-11/include/gtest/gtest.h:58,
                 from C:\Users\wprudencio\gtest-1.7.0-hunter-11\src\gtest-all.cc:39:
C:/Users/wprudencio/gtest-1.7.0-hunter-11/src/gtest-port.cc: In member function 'void testing::internal::ThreadWithParamBase::Join()':
C:/Users/wprudencio/gtest-1.7.0-hunter-11/src/gtest-port.cc:346:38: error: 'thread_' was not declared in this scope
   GTEST_CHECK_(::WaitForSingleObject(thread_.Get(), INFINITE) == WAIT_OBJECT_0)
                                      ^
C:/Users/wprudencio/gtest-1.7.0-hunter-11/include/gtest/internal/gtest-port.h:1250:37: note: in definition of macro 'GTEST_CHECK_'
     if (::testing::internal::IsTrue(condition)) \
                                     ^
In file included from C:\Users\wprudencio\gtest-1.7.0-hunter-11\src\gtest-all.cc:45:0:
C:/Users/wprudencio/gtest-1.7.0-hunter-11/src/gtest-port.cc: In function 'bool testing::internal::IsCloseable()':
C:/Users/wprudencio/gtest-1.7.0-hunter-11/src/gtest-port.cc:179:1: warning: control reaches end of non-void function [-Wreturn-type]
 }
 ^
In file included from C:\Users\wprudencio\gtest-1.7.0-hunter-11\src\gtest-all.cc:43:0:
C:/Users/wprudencio/gtest-1.7.0-hunter-11/src/gtest-death-test.cc: At global scope:
C:/Users/wprudencio/gtest-1.7.0-hunter-11/src/gtest-death-test.cc:123:13: warning: 'testing::internal::g_in_fast_death_test_child' defined but not used [-Wunused-variable]
 static bool g_in_fast_death_test_child = false;
             ^
CMakeFiles\gtest.dir\build.make:62: recipe for target 'CMakeFiles/gtest.dir/src/gtest-all.cc.obj' failed
mingw32-make.exe[2]: **\* [CMakeFiles/gtest.dir/src/gtest-all.cc.obj] Error 1
CMakeFiles\Makefile2:66: recipe for target 'CMakeFiles/gtest.dir/all' failed
mingw32-make.exe[1]: **\* [CMakeFiles/gtest.dir/all] Error 2
makefile:126: recipe for target 'all' failed
mingw32-make.exe: **\* [all] Error 2

**Comment by ruslo** [comment]
> The package provided by google compiles without problems.

@WesleyCeraso Can you point to the exact version or SHA1 of commit that's working for you? I've merged last version into: https://github.com/hunter-packages/gtest/releases/tag/v1.7.x-hunter-0 and still see that error.

**Comment by WesleyCeraso** [comment]
I can compile gtest in tag release-1.7.0, I have not realized you were following the master. Once I checked out master I got the same error on the official repository.

**Comment by WesleyCeraso** [comment]
I just used bisect and found the commit that broke the build:

a6340420b9cee27f77c5b91bea807121914a5831 is the first bad commit
commit a6340420b9cee27f77c5b91bea807121914a5831
Author: kosak kosak@google.com
Date:   Mon Mar 24 21:58:25 2014 +0000

```
Implement threading support for gtest on Windows.
Also, stop using localtime(). Instead, use localtime_r() on most systems, localtime_s() on Windows.
```

**Comment by WesleyCeraso** [comment]
I opened an issue in googletest project google/googletest#606

**Comment by WesleyCeraso** [comment]
Package 1.7.0-hunter-6 is the last one to build with MinGW

**Comment by ruslo** [comment]
> I have not realized you were following the master

I've just tried to apply some fixes like https://github.com/forexample/hunter-simple/issues/2

The whole state of GTest is quite unstable from my point of view :) So the last official release is 1.7.0 and it's about 2 years old. This repository was forked from https://chromium.googlesource.com/external/gtest but now looks like official GTest is: https://github.com/google/googletest which has a completely different structure and can't be merged...

> I opened an issue in googletest project google/googletest#606

Great, thank you.

> Package 1.7.0-hunter-6 is the last one to build with MinGW

Thanks for testing, applied: https://github.com/ruslo/hunter/commit/0a47a5eb2d5d357fc820023bcc7ae550a7709dfc

Release with this change: https://github.com/ruslo/hunter/releases/tag/v0.12.17

**Comment by ruslo** [comment]
@WesleyCeraso Closing this since it's not a fork or Hunter issue and workaround applied. Let me know if there will be some other errors.

**Comment by WesleyCeraso** [comment]
Thank you for the support.

**Comment by andoks** [comment]
I am experiencing the same issue with the downgraded package.

I found the issue in the original bug-report (https://github.com/google/googletest/issues/606), and I see the same bug in in the downgraded package's sources.

**Comment by WesleyCeraso** [comment]
@andoks Are you experiencing the same error with 1.7.0-hunter-6?
I'm using the same compiler as you and did not get this error with this version.

**Comment by andoks** [comment]
@WesleyCeraso I tested using ruslos updated HunterGate string (https://github.com/ruslo/hunter/releases/tag/v0.12.17), now I'm quite inexperienced with Hunter in general, so it is quite possible I did something wrong.

In my project I updated the HunterGate stanza, I went into my HUNTER_ROOT and did a git clean -fxd, then ran cmake on my project from a clean build dir.

**Comment by ruslo** [comment]
> I went into my HUNTER_ROOT, and did a git clean -fxd, then ran cmake on my project from a clean build dir

@andoks git version of Hunter is only for developers, there is no need to clone repository if you're user. HunterGate will download tar.gz archive automatically. You need to remove git version of Hunter and allow HunterGate module to do his work or you can update git repository manually (check that you have commit: 0a47a5eb2d5d357fc820023bcc7ae550a7709dfc).

**Comment by andoks** [comment]
@ruslo indeed it seems like I have skimmed the Hunter documentation a bit too quickly. When I removed HUNTER_ROOT, it worked. Sorry for the noise.

Thank you =)

**Comment by ruslo** [comment]
@andoks Also just for your information you can set `HUNTER_STATUS_DEBUG=ON` and see what version downloaded exactly:

```
-- downloading...
     src='https://github.com/hunter-packages/gtest/archive/v1.7.0-hunter-6.tar.gz'
     dst='C:/.../_Base/Download/GTest/1.7.0-hunter-6/64b9314/v1.7.0-hunter-6.tar.gz'
     timeout='none'
```

You should see this one too:

```
-- [hunter] GTEST_ROOT: C:/.../_Base/79f9fe4/deea0cb/2457964/Install (ver.: 1.7.0-hunter-6)
```

**Comment by ruslo** [comment]
@andoks I've added a warning to [README](https://github.com/ruslo/hunter#first-step): `...it means that there is no need to clone this repository in general...` and to [HunterGate](https://github.com/hunter-packages/gate#notes): `...In this case you have to update your git repo manually...`

**Comment by andoks** [comment]
@ruslo nice tip regarding DEBUG=ON, that will definetlly come in handy =)

May I suggest expanding the HUNTER_ROOT variable explanation? e.g 

Set HUNTER_ROOT environment variable (recommended but not mandatory, see other options)

> Set HUNTER_ROOT environment variable (recommended but not mandatory, see other options). This is where Hunter will automatically download the version specified in your configuration (unless you have manually cloned Hunter to this directory, in that case the clone will override the configuration)

Or something similar

**Comment by ruslo** [comment]
> This is where Hunter will automatically download the version specified in your configuration (unless you have manually cloned Hunter to this directory, in that case the clone will override the configuration)

@andoks I've added a link to the README `First steps` section. Now it goes to the `wiki` page with next [warning](https://github.com/ruslo/hunter/wiki/usr.variables#hunter_root):

```
 Warning! If you manually cloned Hunter repository for development purpose the values of URL and SHA1 of HunterGate will be ignored, see notes 
```

**Comment by andoks** [comment]
@ruslo

> I've added a link to the README First steps section. Now it goes to the wiki page with next warning...

That's seems ok too.

The reason I suggested explaining it in clear-text in the bullet itself, is that intuitively (subjective, I know), I would expect that if I set a variable like that, it should actually point to something pre-existing (href SYSROOT when cross-compiling, $PATH etc), and not just some empty "caching" directory, which HUNTER_ROOT might be considered to be.

**Comment by ruslo** [comment]
> The reason I suggested explaining it in clear-text in the bullet itself, is that intuitively (subjective, I know), I would expect that if I set a variable like that, it should actually point to something pre-existing

@andoks How about that:

```
Set HUNTER_ROOT environment variable to an empty directory. This directory will
 be used by HunterGate module for storing packages and utility files. Using
 environment variable is recommended but not mandatory, see other options.
```
- https://github.com/ruslo/hunter#first-step

**Comment by andoks** [comment]
@ruslo yeah, that is a very nice explanation =)

Just to make sure, does it ever make sense to set the HUNTER_ROOT variable to point to a clone of the hunter repository?

**Comment by ruslo** [comment]
> Just to make sure, does it ever make sense to set the HUNTER_ROOT variable to point to a clone of the hunter repository?

@andoks Yes, if you want to add new packages/patches and test them.

**Comment by ruslo** [comment]
> Yes, if you want to add new packages/patches and test them

@andoks Updates:
- HUNTER_ROOT for use and for test: https://github.com/ruslo/hunter/wiki/dev.hunter.root
- Add link for HUNTER_ROOT docs: https://github.com/ruslo/hunter/wiki/usr.variables#hunter_root
- Add link for "adding new package" docs: https://github.com/ruslo/hunter/wiki/usr.adding.new.package#05-test

**Comment by andoks** [comment]
Great work, thanks @ruslo 

In my case the most important update was the clarification regarding HUNTER_ROOT in [first steps](https://github.com/ruslo/hunter#first-step), since I was just "shopping around" for easier ways of handling dependencies in our project. And when "shopping around", I tend to skim through documentation quickly.

And the rest of the updates regarding HUNTER_ROOT will probably come in handy if we decide that we want to try to handle our dependency on [Protobuf](https://github.com/google/protobuf) with Hunter too (hopefully including automatically execution of protoc).

Again, thanks for all the help and support!

**Comment by ruslo** [comment]
>  if we decide that we want to try to handle our dependency on Protobuf with Hunter too

@andoks Just for your information: https://github.com/ruslo/hunter/issues/97
